Document: sudosh2
Title: Debian sudosh2 Manual
Author: <insert document author here>
Abstract: This manual describes what sudosh2 is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/sudosh2/sudosh2.sgml.gz

Format: postscript
Files: /usr/share/doc/sudosh2/sudosh2.ps.gz

Format: text
Files: /usr/share/doc/sudosh2/sudosh2.text.gz

Format: HTML
Index: /usr/share/doc/sudosh2/html/index.html
Files: /usr/share/doc/sudosh2/html/*.html
